require_relative '../config/environment'
require 'rack/test'
require 'database_cleaner'

system("rm db/test.sqlite3")

ActiveRecord::Base.establish_connection(
  :adapter => "sqlite3",
  :database => 'db/test.sqlite3'
)

require_relative '../db/migrate/01_create_posts'
CreatePosts.migrate(:up)
require_relative '../db/migrate/02_create_users'
CreateUsers.migrate(:up)

DatabaseCleaner.strategy = :truncation

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.include Rack::Test::Methods

  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before(:each) do
    DatabaseCleaner.clean
  end
end

# then, whenever you need to clean the DB

def app
  subject
end
